--
-- PostgreSQL database dump
--

\restrict Yy0ilq75Xfg2VTHKkBvkrNpckdbmUmtRKqjZupP7iD9mBzK9u7tjfB34MOmmmYO

-- Dumped from database version 16.13 (Ubuntu 16.13-0ubuntu0.24.04.1)
-- Dumped by pg_dump version 16.13 (Ubuntu 16.13-0ubuntu0.24.04.1)

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

--
-- Name: public; Type: SCHEMA; Schema: -; Owner: bathudi_user
--

-- *not* creating schema, since initdb creates it


ALTER SCHEMA public OWNER TO bathudi_user;

SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- Name: auth_group; Type: TABLE; Schema: public; Owner: bathudi_user
--

CREATE TABLE public.auth_group (
    id integer NOT NULL,
    name character varying(150) NOT NULL
);


ALTER TABLE public.auth_group OWNER TO bathudi_user;

--
-- Name: auth_group_id_seq; Type: SEQUENCE; Schema: public; Owner: bathudi_user
--

ALTER TABLE public.auth_group ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.auth_group_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: auth_group_permissions; Type: TABLE; Schema: public; Owner: bathudi_user
--

CREATE TABLE public.auth_group_permissions (
    id bigint NOT NULL,
    group_id integer NOT NULL,
    permission_id integer NOT NULL
);


ALTER TABLE public.auth_group_permissions OWNER TO bathudi_user;

--
-- Name: auth_group_permissions_id_seq; Type: SEQUENCE; Schema: public; Owner: bathudi_user
--

ALTER TABLE public.auth_group_permissions ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.auth_group_permissions_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: auth_permission; Type: TABLE; Schema: public; Owner: bathudi_user
--

CREATE TABLE public.auth_permission (
    id integer NOT NULL,
    name character varying(255) NOT NULL,
    content_type_id integer NOT NULL,
    codename character varying(100) NOT NULL
);


ALTER TABLE public.auth_permission OWNER TO bathudi_user;

--
-- Name: auth_permission_id_seq; Type: SEQUENCE; Schema: public; Owner: bathudi_user
--

ALTER TABLE public.auth_permission ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.auth_permission_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: auth_user; Type: TABLE; Schema: public; Owner: bathudi_user
--

CREATE TABLE public.auth_user (
    id integer NOT NULL,
    password character varying(128) NOT NULL,
    last_login timestamp with time zone,
    is_superuser boolean NOT NULL,
    username character varying(150) NOT NULL,
    first_name character varying(150) NOT NULL,
    last_name character varying(150) NOT NULL,
    email character varying(254) NOT NULL,
    is_staff boolean NOT NULL,
    is_active boolean NOT NULL,
    date_joined timestamp with time zone NOT NULL
);


ALTER TABLE public.auth_user OWNER TO bathudi_user;

--
-- Name: auth_user_groups; Type: TABLE; Schema: public; Owner: bathudi_user
--

CREATE TABLE public.auth_user_groups (
    id bigint NOT NULL,
    user_id integer NOT NULL,
    group_id integer NOT NULL
);


ALTER TABLE public.auth_user_groups OWNER TO bathudi_user;

--
-- Name: auth_user_groups_id_seq; Type: SEQUENCE; Schema: public; Owner: bathudi_user
--

ALTER TABLE public.auth_user_groups ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.auth_user_groups_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: auth_user_id_seq; Type: SEQUENCE; Schema: public; Owner: bathudi_user
--

ALTER TABLE public.auth_user ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.auth_user_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: auth_user_user_permissions; Type: TABLE; Schema: public; Owner: bathudi_user
--

CREATE TABLE public.auth_user_user_permissions (
    id bigint NOT NULL,
    user_id integer NOT NULL,
    permission_id integer NOT NULL
);


ALTER TABLE public.auth_user_user_permissions OWNER TO bathudi_user;

--
-- Name: auth_user_user_permissions_id_seq; Type: SEQUENCE; Schema: public; Owner: bathudi_user
--

ALTER TABLE public.auth_user_user_permissions ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.auth_user_user_permissions_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: core_application; Type: TABLE; Schema: public; Owner: bathudi_user
--

CREATE TABLE public.core_application (
    id bigint NOT NULL,
    name character varying(100) NOT NULL,
    surname character varying(100) NOT NULL,
    age integer NOT NULL,
    country character varying(100) NOT NULL,
    mobile character varying(20) NOT NULL,
    email character varying(254) NOT NULL,
    education_level character varying(200) NOT NULL,
    previous_school character varying(200) NOT NULL,
    qualification text NOT NULL,
    experience text NOT NULL,
    message text NOT NULL,
    id_document character varying(100),
    matric_certificate character varying(100),
    proof_of_payment character varying(100),
    status character varying(20) NOT NULL,
    fee_verified boolean NOT NULL,
    applied_date timestamp with time zone NOT NULL,
    notes text NOT NULL,
    course_id bigint,
    additional_doc_1 character varying(100),
    additional_doc_2 character varying(100),
    address text NOT NULL,
    course_title character varying(200) NOT NULL,
    id_number character varying(50),
    form_course_id character varying(100) NOT NULL,
    rejection_reason text,
    payment_reference character varying(100)
);


ALTER TABLE public.core_application OWNER TO bathudi_user;

--
-- Name: core_application_id_seq; Type: SEQUENCE; Schema: public; Owner: bathudi_user
--

ALTER TABLE public.core_application ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.core_application_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: core_course; Type: TABLE; Schema: public; Owner: bathudi_user
--

CREATE TABLE public.core_course (
    id bigint NOT NULL,
    title character varying(200) NOT NULL,
    short_title character varying(100) NOT NULL,
    description text NOT NULL,
    short_description character varying(300) NOT NULL,
    duration character varying(100) NOT NULL,
    fee numeric(10,2) NOT NULL,
    registration_fee numeric(10,2) NOT NULL,
    level character varying(20) NOT NULL,
    curriculum text NOT NULL,
    prerequisites text NOT NULL,
    requirements text NOT NULL,
    career_opportunities text NOT NULL,
    is_featured boolean NOT NULL,
    is_active boolean NOT NULL,
    is_math_required boolean NOT NULL,
    image character varying(100),
    image_url character varying(200) NOT NULL,
    display_order integer NOT NULL,
    created_at timestamp with time zone NOT NULL,
    updated_at timestamp with time zone NOT NULL,
    assessment_fee numeric(10,2) NOT NULL,
    course_pdf character varying(100),
    credits integer NOT NULL,
    deposit_amount numeric(10,2) NOT NULL,
    monthly_payment numeric(10,2) NOT NULL,
    total_payment numeric(10,2) NOT NULL,
    course_pdf_url character varying(500) NOT NULL
);


ALTER TABLE public.core_course OWNER TO bathudi_user;

--
-- Name: core_course_id_seq; Type: SEQUENCE; Schema: public; Owner: bathudi_user
--

ALTER TABLE public.core_course ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.core_course_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: core_courserequirement; Type: TABLE; Schema: public; Owner: bathudi_user
--

CREATE TABLE public.core_courserequirement (
    id bigint NOT NULL,
    type character varying(50) NOT NULL,
    description character varying(200) NOT NULL,
    is_required boolean NOT NULL,
    "order" integer NOT NULL,
    course_id bigint NOT NULL
);


ALTER TABLE public.core_courserequirement OWNER TO bathudi_user;

--
-- Name: core_courserequirement_id_seq; Type: SEQUENCE; Schema: public; Owner: bathudi_user
--

ALTER TABLE public.core_courserequirement ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.core_courserequirement_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: core_directormessage; Type: TABLE; Schema: public; Owner: bathudi_user
--

CREATE TABLE public.core_directormessage (
    id bigint NOT NULL,
    quote text NOT NULL,
    video_file character varying(100),
    video_url character varying(200) NOT NULL,
    is_active boolean NOT NULL,
    created_at timestamp with time zone NOT NULL,
    updated_at timestamp with time zone NOT NULL
);


ALTER TABLE public.core_directormessage OWNER TO bathudi_user;

--
-- Name: core_directormessage_id_seq; Type: SEQUENCE; Schema: public; Owner: bathudi_user
--

ALTER TABLE public.core_directormessage ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.core_directormessage_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: core_galleryimage; Type: TABLE; Schema: public; Owner: bathudi_user
--

CREATE TABLE public.core_galleryimage (
    id bigint NOT NULL,
    title character varying(200) NOT NULL,
    description text NOT NULL,
    image character varying(100) NOT NULL,
    category character varying(50) NOT NULL,
    upload_date timestamp with time zone NOT NULL,
    is_active boolean NOT NULL
);


ALTER TABLE public.core_galleryimage OWNER TO bathudi_user;

--
-- Name: core_galleryimage_id_seq; Type: SEQUENCE; Schema: public; Owner: bathudi_user
--

ALTER TABLE public.core_galleryimage ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.core_galleryimage_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: core_newsletter; Type: TABLE; Schema: public; Owner: bathudi_user
--

CREATE TABLE public.core_newsletter (
    id bigint NOT NULL,
    email character varying(254) NOT NULL,
    subscribed_at timestamp with time zone NOT NULL,
    is_active boolean NOT NULL
);


ALTER TABLE public.core_newsletter OWNER TO bathudi_user;

--
-- Name: core_newsletter_id_seq; Type: SEQUENCE; Schema: public; Owner: bathudi_user
--

ALTER TABLE public.core_newsletter ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.core_newsletter_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: core_newspost; Type: TABLE; Schema: public; Owner: bathudi_user
--

CREATE TABLE public.core_newspost (
    id bigint NOT NULL,
    title character varying(200) NOT NULL,
    preview_text character varying(300) NOT NULL,
    content text NOT NULL,
    image character varying(100),
    is_published boolean NOT NULL,
    created_at timestamp with time zone NOT NULL,
    updated_at timestamp with time zone NOT NULL
);


ALTER TABLE public.core_newspost OWNER TO bathudi_user;

--
-- Name: core_newspost_id_seq; Type: SEQUENCE; Schema: public; Owner: bathudi_user
--

ALTER TABLE public.core_newspost ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.core_newspost_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: core_student; Type: TABLE; Schema: public; Owner: bathudi_user
--

CREATE TABLE public.core_student (
    id bigint NOT NULL,
    student_id character varying(20) NOT NULL,
    name character varying(100) NOT NULL,
    surname character varying(100) NOT NULL,
    email character varying(254) NOT NULL,
    phone character varying(20) NOT NULL,
    enrollment_date date NOT NULL,
    completion_date date,
    status character varying(20) NOT NULL,
    certificate_id character varying(100) NOT NULL,
    address text NOT NULL,
    application_id bigint,
    course_id bigint,
    user_id integer
);


ALTER TABLE public.core_student OWNER TO bathudi_user;

--
-- Name: core_student_id_seq; Type: SEQUENCE; Schema: public; Owner: bathudi_user
--

ALTER TABLE public.core_student ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.core_student_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: core_teammember; Type: TABLE; Schema: public; Owner: bathudi_user
--

CREATE TABLE public.core_teammember (
    id bigint NOT NULL,
    name character varying(100) NOT NULL,
    "position" character varying(100) NOT NULL,
    bio text NOT NULL,
    email character varying(254) NOT NULL,
    phone character varying(20) NOT NULL,
    image character varying(100) NOT NULL,
    "order" integer NOT NULL,
    is_active boolean NOT NULL,
    facebook character varying(200) NOT NULL,
    twitter character varying(200) NOT NULL,
    linkedin character varying(200) NOT NULL
);


ALTER TABLE public.core_teammember OWNER TO bathudi_user;

--
-- Name: core_teammember_id_seq; Type: SEQUENCE; Schema: public; Owner: bathudi_user
--

ALTER TABLE public.core_teammember ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.core_teammember_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: core_testimonial; Type: TABLE; Schema: public; Owner: bathudi_user
--

CREATE TABLE public.core_testimonial (
    id bigint NOT NULL,
    student_name character varying(100) NOT NULL,
    content text NOT NULL,
    rating integer NOT NULL,
    is_featured boolean NOT NULL,
    created_at timestamp with time zone NOT NULL,
    course_id bigint
);


ALTER TABLE public.core_testimonial OWNER TO bathudi_user;

--
-- Name: core_testimonial_id_seq; Type: SEQUENCE; Schema: public; Owner: bathudi_user
--

ALTER TABLE public.core_testimonial ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.core_testimonial_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: core_video; Type: TABLE; Schema: public; Owner: bathudi_user
--

CREATE TABLE public.core_video (
    id bigint NOT NULL,
    title character varying(200) NOT NULL,
    description text NOT NULL,
    video_file character varying(100),
    video_url character varying(200) NOT NULL,
    thumbnail character varying(100),
    is_active boolean NOT NULL,
    created_at timestamp with time zone NOT NULL
);


ALTER TABLE public.core_video OWNER TO bathudi_user;

--
-- Name: core_video_id_seq; Type: SEQUENCE; Schema: public; Owner: bathudi_user
--

ALTER TABLE public.core_video ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.core_video_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: django_admin_log; Type: TABLE; Schema: public; Owner: bathudi_user
--

CREATE TABLE public.django_admin_log (
    id integer NOT NULL,
    action_time timestamp with time zone NOT NULL,
    object_id text,
    object_repr character varying(200) NOT NULL,
    action_flag smallint NOT NULL,
    change_message text NOT NULL,
    content_type_id integer,
    user_id integer NOT NULL,
    CONSTRAINT django_admin_log_action_flag_check CHECK ((action_flag >= 0))
);


ALTER TABLE public.django_admin_log OWNER TO bathudi_user;

--
-- Name: django_admin_log_id_seq; Type: SEQUENCE; Schema: public; Owner: bathudi_user
--

ALTER TABLE public.django_admin_log ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.django_admin_log_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: django_content_type; Type: TABLE; Schema: public; Owner: bathudi_user
--

CREATE TABLE public.django_content_type (
    id integer NOT NULL,
    app_label character varying(100) NOT NULL,
    model character varying(100) NOT NULL
);


ALTER TABLE public.django_content_type OWNER TO bathudi_user;

--
-- Name: django_content_type_id_seq; Type: SEQUENCE; Schema: public; Owner: bathudi_user
--

ALTER TABLE public.django_content_type ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.django_content_type_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: django_migrations; Type: TABLE; Schema: public; Owner: bathudi_user
--

CREATE TABLE public.django_migrations (
    id bigint NOT NULL,
    app character varying(255) NOT NULL,
    name character varying(255) NOT NULL,
    applied timestamp with time zone NOT NULL
);


ALTER TABLE public.django_migrations OWNER TO bathudi_user;

--
-- Name: django_migrations_id_seq; Type: SEQUENCE; Schema: public; Owner: bathudi_user
--

ALTER TABLE public.django_migrations ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.django_migrations_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: django_session; Type: TABLE; Schema: public; Owner: bathudi_user
--

CREATE TABLE public.django_session (
    session_key character varying(40) NOT NULL,
    session_data text NOT NULL,
    expire_date timestamp with time zone NOT NULL
);


ALTER TABLE public.django_session OWNER TO bathudi_user;

--
-- Name: payfast_payfasttransaction; Type: TABLE; Schema: public; Owner: bathudi_user
--

CREATE TABLE public.payfast_payfasttransaction (
    id bigint NOT NULL,
    payment_id character varying(100) NOT NULL,
    email character varying(254) NOT NULL,
    amount numeric(10,2) NOT NULL,
    status character varying(50) NOT NULL,
    created_at timestamp with time zone NOT NULL,
    raw_response text
);


ALTER TABLE public.payfast_payfasttransaction OWNER TO bathudi_user;

--
-- Name: payfast_payfasttransaction_id_seq; Type: SEQUENCE; Schema: public; Owner: bathudi_user
--

ALTER TABLE public.payfast_payfasttransaction ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.payfast_payfasttransaction_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Data for Name: auth_group; Type: TABLE DATA; Schema: public; Owner: bathudi_user
--

COPY public.auth_group (id, name) FROM stdin;
\.


--
-- Data for Name: auth_group_permissions; Type: TABLE DATA; Schema: public; Owner: bathudi_user
--

COPY public.auth_group_permissions (id, group_id, permission_id) FROM stdin;
\.


--
-- Data for Name: auth_permission; Type: TABLE DATA; Schema: public; Owner: bathudi_user
--

COPY public.auth_permission (id, name, content_type_id, codename) FROM stdin;
1	Can add log entry	1	add_logentry
2	Can change log entry	1	change_logentry
3	Can delete log entry	1	delete_logentry
4	Can view log entry	1	view_logentry
5	Can add permission	2	add_permission
6	Can change permission	2	change_permission
7	Can delete permission	2	delete_permission
8	Can view permission	2	view_permission
9	Can add group	3	add_group
10	Can change group	3	change_group
11	Can delete group	3	delete_group
12	Can view group	3	view_group
13	Can add user	4	add_user
14	Can change user	4	change_user
15	Can delete user	4	delete_user
16	Can view user	4	view_user
17	Can add content type	5	add_contenttype
18	Can change content type	5	change_contenttype
19	Can delete content type	5	delete_contenttype
20	Can view content type	5	view_contenttype
21	Can add session	6	add_session
22	Can change session	6	change_session
23	Can delete session	6	delete_session
24	Can view session	6	view_session
25	Can add course	7	add_course
26	Can change course	7	change_course
27	Can delete course	7	delete_course
28	Can view course	7	view_course
29	Can add director message	8	add_directormessage
30	Can change director message	8	change_directormessage
31	Can delete director message	8	delete_directormessage
32	Can view director message	8	view_directormessage
33	Can add gallery image	9	add_galleryimage
34	Can change gallery image	9	change_galleryimage
35	Can delete gallery image	9	delete_galleryimage
36	Can view gallery image	9	view_galleryimage
37	Can add newsletter	10	add_newsletter
38	Can change newsletter	10	change_newsletter
39	Can delete newsletter	10	delete_newsletter
40	Can view newsletter	10	view_newsletter
41	Can add news post	11	add_newspost
42	Can change news post	11	change_newspost
43	Can delete news post	11	delete_newspost
44	Can view news post	11	view_newspost
45	Can add team member	12	add_teammember
46	Can change team member	12	change_teammember
47	Can delete team member	12	delete_teammember
48	Can view team member	12	view_teammember
49	Can add video	13	add_video
50	Can change video	13	change_video
51	Can delete video	13	delete_video
52	Can view video	13	view_video
53	Can add application	14	add_application
54	Can change application	14	change_application
55	Can delete application	14	delete_application
56	Can view application	14	view_application
57	Can add course requirement	15	add_courserequirement
58	Can change course requirement	15	change_courserequirement
59	Can delete course requirement	15	delete_courserequirement
60	Can view course requirement	15	view_courserequirement
61	Can add student	16	add_student
62	Can change student	16	change_student
63	Can delete student	16	delete_student
64	Can view student	16	view_student
65	Can add testimonial	17	add_testimonial
66	Can change testimonial	17	change_testimonial
67	Can delete testimonial	17	delete_testimonial
68	Can view testimonial	17	view_testimonial
69	Can add payfast transaction	18	add_payfasttransaction
70	Can change payfast transaction	18	change_payfasttransaction
71	Can delete payfast transaction	18	delete_payfasttransaction
72	Can view payfast transaction	18	view_payfasttransaction
\.


--
-- Data for Name: auth_user; Type: TABLE DATA; Schema: public; Owner: bathudi_user
--

COPY public.auth_user (id, password, last_login, is_superuser, username, first_name, last_name, email, is_staff, is_active, date_joined) FROM stdin;
1	pbkdf2_sha256$600000$lYQAuQ9iNGTU2p9Rbbdsl9$5SWi4AemYBiVqLc5y3VcD8SvzfemZ1Q1+6ZZL8Db4lg=	2026-03-13 18:26:48.184582+01	t	admin			admin@example.com	t	t	2026-03-13 14:13:32.345553+01
\.


--
-- Data for Name: auth_user_groups; Type: TABLE DATA; Schema: public; Owner: bathudi_user
--

COPY public.auth_user_groups (id, user_id, group_id) FROM stdin;
\.


--
-- Data for Name: auth_user_user_permissions; Type: TABLE DATA; Schema: public; Owner: bathudi_user
--

COPY public.auth_user_user_permissions (id, user_id, permission_id) FROM stdin;
\.


--
-- Data for Name: core_application; Type: TABLE DATA; Schema: public; Owner: bathudi_user
--

COPY public.core_application (id, name, surname, age, country, mobile, email, education_level, previous_school, qualification, experience, message, id_document, matric_certificate, proof_of_payment, status, fee_verified, applied_date, notes, course_id, additional_doc_1, additional_doc_2, address, course_title, id_number, form_course_id, rejection_reason, payment_reference) FROM stdin;
2	Muzi	Ndlovu	26	Zimbabwe	0773074487	muzidean14@gmail.com	Grade 12 (Matric)	Ridgeway				applications/id/id_documents/2026/03/13/XTRG_QUOTEMS_-_2026-03-12T112715.748_OM8H9GD.pdf	applications/matric/matric_certificates/2026/03/13/MSU_Invoice_VHmXQGA.pdf	applications/pop/proof_of_payments/2026/03/13/Cemetery_ry_fee_QG1Uyba.pdf	approved	t	2026-03-13 19:49:56.554381+01		3			24James Court	Occupational Certificate: Automotive Suspension Fitter	08-2067658A73	3	\N	\N
1	Brian D	Magagula	23	South Africa	+27831234567	example@gmail.com	Degree	St Columba's High				applications/id/id_documents/2026/03/13/fdjbabwbcw1_eppXDwb.pdf	applications/matric/matric_certificates/2026/03/13/fdjbabwbcw_9KBQsxB.pdf	applications/pop/proof_of_payments/2026/03/13/Funeral_kXaLfWQ.pdf	pending	t	2026-03-13 19:22:25.035098+01		3			209 Nguboyenja	Occupational Certificate: Automotive Suspension Fitter	08-980887H73	3	\N	\N
\.


--
-- Data for Name: core_course; Type: TABLE DATA; Schema: public; Owner: bathudi_user
--

COPY public.core_course (id, title, short_title, description, short_description, duration, fee, registration_fee, level, curriculum, prerequisites, requirements, career_opportunities, is_featured, is_active, is_math_required, image, image_url, display_order, created_at, updated_at, assessment_fee, course_pdf, credits, deposit_amount, monthly_payment, total_payment, course_pdf_url) FROM stdin;
1	Occupational Certificate: Automotive Engine Repairer	Automotive Engine Repairer	Specialized training program focused on automotive engine fitting, assembly, and repair. Students learn engine diagnosis, component fitting, assembly techniques, and testing procedures for various engine types.	Specialized training program focused on automotive engine fitting, assembly, and repair.	36 months	0.00	661.25	beginner	Module 1: Engine Fundamentals\r\n\r\n- Engine types and classifications\r\n\r\n- Engine components and functions\r\n\r\n- Engine measurement and specifications\r\n\r\nModule 2: Engine Disassembly\r\n\r\n- Safe disassembly procedures\r\n\r\n- Component identification\r\n\r\n- Damage assessment\r\n\r\nModule 3: Engine Assembly\r\n\r\n- Component fitting techniques\r\n\r\n- Torque specifications\r\n\r\n- Clearance measurements\r\n\r\nModule 4: Engine Testing\r\n\r\n- Compression testing\r\n\r\n- Leak-down testing\r\n\r\n- Performance evaluation		Basic understanding of mechanical systems. Interest in engine technology.	Grade 12 with Mathematics/Mathematical Literacy OR any N certification (N2/N3/N4). Good hand-eye coordination and mechanical aptitude.	f	t	f	courses/25.jpeg		-10	2026-03-13 18:38:10.765354+01	2026-03-13 18:38:10.765384+01	661.25	course_pdfs/Automotive_Engine_Fitter.pdf	540	0.00	0.00	0.00	
3	Occupational Certificate: Automotive Suspension Fitter	Suspension Specialist	Specialized training program focusing on automotive suspension systems, steering components, and wheel alignment. Students learn to diagnose, repair, and maintain suspension systems for various vehicle types.	Master automotive suspension and steering system repair	9 months	0.00	661.25	beginner	Module 1: Suspension Fundamentals\r\n\r\n- Suspension types and designs\r\n\r\n- Shock absorbers and struts\r\n\r\n- Springs and stabilizers\r\n\r\nModule 2: Steering Systems\r\n\r\n- Manual and power steering\r\n\r\n- Steering linkage\r\n\r\n- Steering geometry\r\n\r\nModule 3: Wheel Alignment\r\n\r\n- Alignment principles\r\n\r\n- Alignment equipment\r\n\r\n- Adjustment procedures\r\n\r\nModule 4: Diagnosis and Repair\r\n\r\n- Suspension troubleshooting\r\n\r\n- Component replacement\r\n\r\n- System testing	Basic automotive knowledge. Understanding of vehicle dynamics.	Grade 12 certificate. Previous mechanical experience beneficial.	-Automotive Technician\r\nStart your career as a professional automotive technician with skills gained from this course\r\n-Diagnostic Specialist\r\nStart your career as a professional diagnostic specialist with skills gained from this course\r\n-Workshop Manager\r\nStart your career as a professional workshop manager with skills gained from this course	f	t	f	courses/3.jpg		-4	2026-03-13 18:44:51.561352+01	2026-03-13 18:44:51.561372+01	661.25	course_pdfs/Automotive_Engine_Fitter_QIXT69m.pdf	123	0.00	0.00	0.00	
4	Occupational Certificate: Automotive Workshop Assistant	Workshop Assistant	Foundational training program for automotive workshop operations. Covers workshop safety, basic maintenance, tool usage, and assistance procedures for automotive repair and maintenance.	Start your career as an automotive workshop assistant	14 months	0.00	661.25	beginner	Course Curriculum\r\nModule 1: Workshop Basics\r\n\r\n- Workshop safety procedures\r\n\r\n- Tool identification and usage\r\n\r\n- Workshop organization\r\n\r\nModule 2: Vehicle Maintenance\r\n\r\n- Basic maintenance procedures\r\n\r\n- Fluid checks and changes\r\n\r\n- Tire service\r\n\r\nModule 3: Assistance Skills\r\n\r\n- Technician assistance\r\n\r\n- Parts handling\r\n\r\n- Customer service\r\n\r\nModule 4: Workshop Operations\r\n\r\n- Inventory management\r\n\r\n- Workshop cleaning\r\n\r\n- Safety compliance	No prior experience required. Interest in automotive work.	Grade 12 OR Grade 10 with relevant experience. Willingness to learn and work in a team.	-Automotive Technician\r\nStart your career as a professional automotive technician with skills gained from this course\r\n-Diagnostic Specialist\r\nStart your career as a professional diagnostic specialist with skills gained from this course\r\n-Workshop Manager\r\nStart your career as a professional workshop manager with skills gained from this course	f	t	f	courses/4.jpg		4	2026-03-13 18:47:23.469763+01	2026-03-13 18:47:23.469812+01	661.25	course_pdfs/Automotive_Workshop_Assistant.pdf	182	0.00	0.00	0.00	
2	Occupational Certificate: Automotive Clutch and Brake Repairer	Automotive Clutch and Brake Repairer	Comprehensive training program specializing in automotive clutch and brake systems. Covers diagnosis, repair, and maintenance of braking systems, clutch assemblies, and related components.	Specialize in automotive clutch and brake system repair	12 months	0.00	661.25	beginner	Module 1: Brake System Fundamentals\r\n\r\n- Hydraulic brake systems\r\n\r\n- Disc and drum brakes\r\n\r\n- ABS and electronic systems\r\n\r\nModule 2: Clutch Systems\r\n\r\n- Manual transmission clutches\r\n\r\n- Hydraulic clutch systems\r\n\r\n- Automatic transmission components\r\n\r\nModule 3: Diagnosis and Repair\r\n\r\n- Brake system diagnosis\r\n\r\n- Clutch system troubleshooting\r\n\r\n- Component replacement\r\n\r\nModule 4: Safety and Testing\r\n\r\n- Brake testing procedures\r\n\r\n- Safety standards\r\n\r\n- Quality control	Basic mechanical knowledge. Attention to detail for safety-critical systems.	Grade 9 or Year 4 (ABET Level 4). No mathematics requirement.	-Automotive Technician\r\nStart your career as a professional automotive technician with skills gained from this course\r\n-Diagnostic Specialist\r\nStart your career as a professional diagnostic specialist with skills gained from this course\r\n-Workshop Manager\r\nStart your career as a professional workshop manager with skills gained from this course	f	t	f	courses/2.jpg		2	2026-03-13 18:41:56.409292+01	2026-03-13 18:48:09.559561+01	661.25	course_pdfs/Automotive_Clutch_and_Brake_Repairer.pdf	166	0.00	0.00	0.00	
\.


--
-- Data for Name: core_courserequirement; Type: TABLE DATA; Schema: public; Owner: bathudi_user
--

COPY public.core_courserequirement (id, type, description, is_required, "order", course_id) FROM stdin;
\.


--
-- Data for Name: core_directormessage; Type: TABLE DATA; Schema: public; Owner: bathudi_user
--

COPY public.core_directormessage (id, quote, video_file, video_url, is_active, created_at, updated_at) FROM stdin;
1	WELCOME TO BATHUDI!!!!	videos/director/bathudi_video.mp4		t	2026-03-17 11:11:29.088098+01	2026-03-22 18:51:21.388233+01
\.


--
-- Data for Name: core_galleryimage; Type: TABLE DATA; Schema: public; Owner: bathudi_user
--

COPY public.core_galleryimage (id, title, description, image, category, upload_date, is_active) FROM stdin;
\.


--
-- Data for Name: core_newsletter; Type: TABLE DATA; Schema: public; Owner: bathudi_user
--

COPY public.core_newsletter (id, email, subscribed_at, is_active) FROM stdin;
\.


--
-- Data for Name: core_newspost; Type: TABLE DATA; Schema: public; Owner: bathudi_user
--

COPY public.core_newspost (id, title, preview_text, content, image, is_published, created_at, updated_at) FROM stdin;
3	New Week!!	Join Us for a week full of learning and gaining industrial experience only at BaThUdi AuToMoTiVe!!!	Our workshop continues this week with students working on real-world projects, gaining the hands-on experience that sets skilled professionals apart.\r\n\r\nWhat's Happening This Week\r\nLive Projects: Students are actively working on client deliverables, applying classroom knowledge to real requirements\r\n\r\nMentorship Sessions: Industry professionals on-site to guide, review, and share insights\r\n\r\nCollaborative Environment: Work alongside peers, solve problems together, and build your	news/10.jpg	t	2026-03-22 19:02:11.946084+01	2026-03-22 19:02:11.946125+01
4	From Learning to Doing: Students in Action	Real experience, real results—see how our workshop is preparing students for the industry	Theory teaches you the rules. Experience teaches you the game.\r\n\r\nThis week, our workshop students are stepping beyond textbooks and into the real work that shapes careers. From troubleshooting live code to meeting client requirements, they're building more than projects—they're building professional instincts.\r\n\r\nReady to Gain Real Experience?\r\nWhether you're a current student or looking to start, the workshop is where you build skills that matter.\r\n\r\nGet in touch to learn more about upcoming sessions.	news/8f7d1b3b-9512-4f82-b41b-9b9f812c2d7c.jpg	t	2026-03-22 19:04:38.139799+01	2026-03-22 19:04:38.139885+01
\.


--
-- Data for Name: core_student; Type: TABLE DATA; Schema: public; Owner: bathudi_user
--

COPY public.core_student (id, student_id, name, surname, email, phone, enrollment_date, completion_date, status, certificate_id, address, application_id, course_id, user_id) FROM stdin;
1	STU0002	Muzi	Ndlovu	muzidean14@gmail.com	0773074487	2026-03-13	\N	enrolled		24James Court	2	3	\N
\.


--
-- Data for Name: core_teammember; Type: TABLE DATA; Schema: public; Owner: bathudi_user
--

COPY public.core_teammember (id, name, "position", bio, email, phone, image, "order", is_active, facebook, twitter, linkedin) FROM stdin;
1	Ignatia Sekonyela	CEO and Founder		info@bathudi.co.za	+27 68 917 6294	team/7.jpg	1	t			
\.


--
-- Data for Name: core_testimonial; Type: TABLE DATA; Schema: public; Owner: bathudi_user
--

COPY public.core_testimonial (id, student_name, content, rating, is_featured, created_at, course_id) FROM stdin;
\.


--
-- Data for Name: core_video; Type: TABLE DATA; Schema: public; Owner: bathudi_user
--

COPY public.core_video (id, title, description, video_file, video_url, thumbnail, is_active, created_at) FROM stdin;
\.


--
-- Data for Name: django_admin_log; Type: TABLE DATA; Schema: public; Owner: bathudi_user
--

COPY public.django_admin_log (id, action_time, object_id, object_repr, action_flag, change_message, content_type_id, user_id) FROM stdin;
1	2026-03-13 18:38:10.779241+01	1	Occupational Certificate: Automotive Engine Repairer	1	[{"added": {}}]	7	1
2	2026-03-13 18:41:56.41499+01	2	Occupational Certificate: Automotive Clutch and Brake Repairer	1	[{"added": {}}]	7	1
3	2026-03-13 18:44:51.566743+01	3	Occupational Certificate: Automotive Suspension Fitter	1	[{"added": {}}]	7	1
4	2026-03-13 18:47:23.473574+01	4	Occupational Certificate: Automotive Workshop Assistant	1	[{"added": {}}]	7	1
5	2026-03-13 18:48:09.567346+01	2	Occupational Certificate: Automotive Clutch and Brake Repairer	2	[{"changed": {"fields": ["Credits"]}}]	7	1
6	2026-03-13 18:50:08.358329+01	1	Ignatia Sekonyela - CEO and Founder	1	[{"added": {}}]	12	1
\.


--
-- Data for Name: django_content_type; Type: TABLE DATA; Schema: public; Owner: bathudi_user
--

COPY public.django_content_type (id, app_label, model) FROM stdin;
1	admin	logentry
2	auth	permission
3	auth	group
4	auth	user
5	contenttypes	contenttype
6	sessions	session
7	core	course
8	core	directormessage
9	core	galleryimage
10	core	newsletter
11	core	newspost
12	core	teammember
13	core	video
14	core	application
15	core	courserequirement
16	core	student
17	core	testimonial
18	payfast	payfasttransaction
\.


--
-- Data for Name: django_migrations; Type: TABLE DATA; Schema: public; Owner: bathudi_user
--

COPY public.django_migrations (id, app, name, applied) FROM stdin;
1	contenttypes	0001_initial	2026-03-13 14:12:17.944699+01
2	auth	0001_initial	2026-03-13 14:12:18.114774+01
3	admin	0001_initial	2026-03-13 14:12:18.164572+01
4	admin	0002_logentry_remove_auto_add	2026-03-13 14:12:18.175208+01
5	admin	0003_logentry_add_action_flag_choices	2026-03-13 14:12:18.188615+01
6	contenttypes	0002_remove_content_type_name	2026-03-13 14:12:18.211125+01
7	auth	0002_alter_permission_name_max_length	2026-03-13 14:12:18.226287+01
8	auth	0003_alter_user_email_max_length	2026-03-13 14:12:18.241521+01
9	auth	0004_alter_user_username_opts	2026-03-13 14:12:18.255124+01
10	auth	0005_alter_user_last_login_null	2026-03-13 14:12:18.271699+01
11	auth	0006_require_contenttypes_0002	2026-03-13 14:12:18.275724+01
12	auth	0007_alter_validators_add_error_messages	2026-03-13 14:12:18.295645+01
13	auth	0008_alter_user_username_max_length	2026-03-13 14:12:18.318662+01
14	auth	0009_alter_user_last_name_max_length	2026-03-13 14:12:18.337772+01
15	auth	0010_alter_group_name_max_length	2026-03-13 14:12:18.355048+01
16	auth	0011_update_proxy_permissions	2026-03-13 14:12:18.371703+01
17	auth	0012_alter_user_first_name_max_length	2026-03-13 14:12:18.388527+01
18	core	0001_initial	2026-03-13 14:12:18.618171+01
19	core	0002_course_assessment_fee_course_course_pdf_and_more	2026-03-13 14:12:18.68781+01
20	core	0003_course_course_pdf_url	2026-03-13 14:12:18.703236+01
21	core	0004_application_additional_doc_1_and_more	2026-03-13 14:12:18.782868+01
22	core	0005_application_form_course_id_and_more	2026-03-13 14:12:18.889053+01
23	core	0006_alter_application_country_and_more	2026-03-13 14:12:18.932224+01
24	core	0007_application_rejection_reason	2026-03-13 14:12:18.957288+01
25	sessions	0001_initial	2026-03-13 14:12:18.988551+01
26	payfast	0001_initial	2026-03-14 21:08:02.466828+01
27	core	0008_application_payment_reference	2026-03-19 20:46:21.730346+01
\.


--
-- Data for Name: django_session; Type: TABLE DATA; Schema: public; Owner: bathudi_user
--

COPY public.django_session (session_key, session_data, expire_date) FROM stdin;
8yzysz9o06rd7l0oroji8a3tcgms2lmd	.eJxVjDsOwjAQBe_iGln-4XUo6XMGa9fe4ACypTipEHeHSCmgfTPzXiLitpa4dV7inMVFaHH63QjTg-sO8h3rrcnU6rrMJHdFHrTLsWV-Xg_376BgL996MoxOgSOVwSsMAMgpmDOh8oTBgx5cSMYqGqyaAnkAw-ysNhbZGifeH9j-NzU:1w16Hg:Dz1Qxza7FZudBCa1iPs3OgpCS8kzS8UDbL9AGSZ_8Uk	2026-03-27 18:26:48.197025+01
\.


--
-- Data for Name: payfast_payfasttransaction; Type: TABLE DATA; Schema: public; Owner: bathudi_user
--

COPY public.payfast_payfasttransaction (id, payment_id, email, amount, status, created_at, raw_response) FROM stdin;
1	PAY-1773524090	r5tyhty@fghh.hjt	661.25	initiated	2026-03-14 22:34:50.44704+01	\N
2	PAY-1773524323	jy@dgg.ght	661.25	initiated	2026-03-14 22:38:43.991567+01	\N
3	PAY-1773525017	brianmagagula5@gmail.com	661.25	initiated	2026-03-14 22:50:17.901629+01	\N
4	PAY-1773525126	muzidean@icloud.com	661.25	initiated	2026-03-14 22:52:06.7667+01	\N
5	PAY-1773600659	muzidean@icloud.com	661.25	initiated	2026-03-15 19:50:59.465836+01	\N
6	PAY-1773659570	muzidean@icloud.com	661.25	initiated	2026-03-16 12:12:50.043962+01	\N
7	PAY-1773840995	muzidean@icloud.com	661.25	initiated	2026-03-18 14:36:35.170826+01	\N
8	PAY-1773948154	muzidean@icloud.com	661.25	initiated	2026-03-19 20:22:34.440887+01	\N
9	PAY-1773987084	n0230442w@students.nust.ac.zw	661.25	initiated	2026-03-20 07:11:24.946627+01	\N
10	PAY-1773996586	escanbcc@gmail.com	661.25	initiated	2026-03-20 09:49:46.321474+01	\N
11	PAY-1774281893	test@example.com	661.25	initiated	2026-03-23 17:04:53.649208+01	\N
12	PAY-1774282729	test@example.com	661.25	initiated	2026-03-23 17:18:49.546052+01	\N
13	PAY-1774346399	muzidean@icloud.com	661.25	initiated	2026-03-24 10:59:59.782934+01	\N
\.


--
-- Name: auth_group_id_seq; Type: SEQUENCE SET; Schema: public; Owner: bathudi_user
--

SELECT pg_catalog.setval('public.auth_group_id_seq', 1, false);


--
-- Name: auth_group_permissions_id_seq; Type: SEQUENCE SET; Schema: public; Owner: bathudi_user
--

SELECT pg_catalog.setval('public.auth_group_permissions_id_seq', 1, false);


--
-- Name: auth_permission_id_seq; Type: SEQUENCE SET; Schema: public; Owner: bathudi_user
--

SELECT pg_catalog.setval('public.auth_permission_id_seq', 72, true);


--
-- Name: auth_user_groups_id_seq; Type: SEQUENCE SET; Schema: public; Owner: bathudi_user
--

SELECT pg_catalog.setval('public.auth_user_groups_id_seq', 1, false);


--
-- Name: auth_user_id_seq; Type: SEQUENCE SET; Schema: public; Owner: bathudi_user
--

SELECT pg_catalog.setval('public.auth_user_id_seq', 3, true);


--
-- Name: auth_user_user_permissions_id_seq; Type: SEQUENCE SET; Schema: public; Owner: bathudi_user
--

SELECT pg_catalog.setval('public.auth_user_user_permissions_id_seq', 1, false);


--
-- Name: core_application_id_seq; Type: SEQUENCE SET; Schema: public; Owner: bathudi_user
--

SELECT pg_catalog.setval('public.core_application_id_seq', 2, true);


--
-- Name: core_course_id_seq; Type: SEQUENCE SET; Schema: public; Owner: bathudi_user
--

SELECT pg_catalog.setval('public.core_course_id_seq', 4, true);


--
-- Name: core_courserequirement_id_seq; Type: SEQUENCE SET; Schema: public; Owner: bathudi_user
--

SELECT pg_catalog.setval('public.core_courserequirement_id_seq', 1, false);


--
-- Name: core_directormessage_id_seq; Type: SEQUENCE SET; Schema: public; Owner: bathudi_user
--

SELECT pg_catalog.setval('public.core_directormessage_id_seq', 1, true);


--
-- Name: core_galleryimage_id_seq; Type: SEQUENCE SET; Schema: public; Owner: bathudi_user
--

SELECT pg_catalog.setval('public.core_galleryimage_id_seq', 2, true);


--
-- Name: core_newsletter_id_seq; Type: SEQUENCE SET; Schema: public; Owner: bathudi_user
--

SELECT pg_catalog.setval('public.core_newsletter_id_seq', 1, false);


--
-- Name: core_newspost_id_seq; Type: SEQUENCE SET; Schema: public; Owner: bathudi_user
--

SELECT pg_catalog.setval('public.core_newspost_id_seq', 4, true);


--
-- Name: core_student_id_seq; Type: SEQUENCE SET; Schema: public; Owner: bathudi_user
--

SELECT pg_catalog.setval('public.core_student_id_seq', 1, true);


--
-- Name: core_teammember_id_seq; Type: SEQUENCE SET; Schema: public; Owner: bathudi_user
--

SELECT pg_catalog.setval('public.core_teammember_id_seq', 1, true);


--
-- Name: core_testimonial_id_seq; Type: SEQUENCE SET; Schema: public; Owner: bathudi_user
--

SELECT pg_catalog.setval('public.core_testimonial_id_seq', 1, false);


--
-- Name: core_video_id_seq; Type: SEQUENCE SET; Schema: public; Owner: bathudi_user
--

SELECT pg_catalog.setval('public.core_video_id_seq', 1, false);


--
-- Name: django_admin_log_id_seq; Type: SEQUENCE SET; Schema: public; Owner: bathudi_user
--

SELECT pg_catalog.setval('public.django_admin_log_id_seq', 6, true);


--
-- Name: django_content_type_id_seq; Type: SEQUENCE SET; Schema: public; Owner: bathudi_user
--

SELECT pg_catalog.setval('public.django_content_type_id_seq', 18, true);


--
-- Name: django_migrations_id_seq; Type: SEQUENCE SET; Schema: public; Owner: bathudi_user
--

SELECT pg_catalog.setval('public.django_migrations_id_seq', 27, true);


--
-- Name: payfast_payfasttransaction_id_seq; Type: SEQUENCE SET; Schema: public; Owner: bathudi_user
--

SELECT pg_catalog.setval('public.payfast_payfasttransaction_id_seq', 13, true);


--
-- Name: auth_group auth_group_name_key; Type: CONSTRAINT; Schema: public; Owner: bathudi_user
--

ALTER TABLE ONLY public.auth_group
    ADD CONSTRAINT auth_group_name_key UNIQUE (name);


--
-- Name: auth_group_permissions auth_group_permissions_group_id_permission_id_0cd325b0_uniq; Type: CONSTRAINT; Schema: public; Owner: bathudi_user
--

ALTER TABLE ONLY public.auth_group_permissions
    ADD CONSTRAINT auth_group_permissions_group_id_permission_id_0cd325b0_uniq UNIQUE (group_id, permission_id);


--
-- Name: auth_group_permissions auth_group_permissions_pkey; Type: CONSTRAINT; Schema: public; Owner: bathudi_user
--

ALTER TABLE ONLY public.auth_group_permissions
    ADD CONSTRAINT auth_group_permissions_pkey PRIMARY KEY (id);


--
-- Name: auth_group auth_group_pkey; Type: CONSTRAINT; Schema: public; Owner: bathudi_user
--

ALTER TABLE ONLY public.auth_group
    ADD CONSTRAINT auth_group_pkey PRIMARY KEY (id);


--
-- Name: auth_permission auth_permission_content_type_id_codename_01ab375a_uniq; Type: CONSTRAINT; Schema: public; Owner: bathudi_user
--

ALTER TABLE ONLY public.auth_permission
    ADD CONSTRAINT auth_permission_content_type_id_codename_01ab375a_uniq UNIQUE (content_type_id, codename);


--
-- Name: auth_permission auth_permission_pkey; Type: CONSTRAINT; Schema: public; Owner: bathudi_user
--

ALTER TABLE ONLY public.auth_permission
    ADD CONSTRAINT auth_permission_pkey PRIMARY KEY (id);


--
-- Name: auth_user_groups auth_user_groups_pkey; Type: CONSTRAINT; Schema: public; Owner: bathudi_user
--

ALTER TABLE ONLY public.auth_user_groups
    ADD CONSTRAINT auth_user_groups_pkey PRIMARY KEY (id);


--
-- Name: auth_user_groups auth_user_groups_user_id_group_id_94350c0c_uniq; Type: CONSTRAINT; Schema: public; Owner: bathudi_user
--

ALTER TABLE ONLY public.auth_user_groups
    ADD CONSTRAINT auth_user_groups_user_id_group_id_94350c0c_uniq UNIQUE (user_id, group_id);


--
-- Name: auth_user auth_user_pkey; Type: CONSTRAINT; Schema: public; Owner: bathudi_user
--

ALTER TABLE ONLY public.auth_user
    ADD CONSTRAINT auth_user_pkey PRIMARY KEY (id);


--
-- Name: auth_user_user_permissions auth_user_user_permissions_pkey; Type: CONSTRAINT; Schema: public; Owner: bathudi_user
--

ALTER TABLE ONLY public.auth_user_user_permissions
    ADD CONSTRAINT auth_user_user_permissions_pkey PRIMARY KEY (id);


--
-- Name: auth_user_user_permissions auth_user_user_permissions_user_id_permission_id_14a6b632_uniq; Type: CONSTRAINT; Schema: public; Owner: bathudi_user
--

ALTER TABLE ONLY public.auth_user_user_permissions
    ADD CONSTRAINT auth_user_user_permissions_user_id_permission_id_14a6b632_uniq UNIQUE (user_id, permission_id);


--
-- Name: auth_user auth_user_username_key; Type: CONSTRAINT; Schema: public; Owner: bathudi_user
--

ALTER TABLE ONLY public.auth_user
    ADD CONSTRAINT auth_user_username_key UNIQUE (username);


--
-- Name: core_application core_application_payment_reference_key; Type: CONSTRAINT; Schema: public; Owner: bathudi_user
--

ALTER TABLE ONLY public.core_application
    ADD CONSTRAINT core_application_payment_reference_key UNIQUE (payment_reference);


--
-- Name: core_application core_application_pkey; Type: CONSTRAINT; Schema: public; Owner: bathudi_user
--

ALTER TABLE ONLY public.core_application
    ADD CONSTRAINT core_application_pkey PRIMARY KEY (id);


--
-- Name: core_course core_course_pkey; Type: CONSTRAINT; Schema: public; Owner: bathudi_user
--

ALTER TABLE ONLY public.core_course
    ADD CONSTRAINT core_course_pkey PRIMARY KEY (id);


--
-- Name: core_courserequirement core_courserequirement_pkey; Type: CONSTRAINT; Schema: public; Owner: bathudi_user
--

ALTER TABLE ONLY public.core_courserequirement
    ADD CONSTRAINT core_courserequirement_pkey PRIMARY KEY (id);


--
-- Name: core_directormessage core_directormessage_pkey; Type: CONSTRAINT; Schema: public; Owner: bathudi_user
--

ALTER TABLE ONLY public.core_directormessage
    ADD CONSTRAINT core_directormessage_pkey PRIMARY KEY (id);


--
-- Name: core_galleryimage core_galleryimage_pkey; Type: CONSTRAINT; Schema: public; Owner: bathudi_user
--

ALTER TABLE ONLY public.core_galleryimage
    ADD CONSTRAINT core_galleryimage_pkey PRIMARY KEY (id);


--
-- Name: core_newsletter core_newsletter_email_key; Type: CONSTRAINT; Schema: public; Owner: bathudi_user
--

ALTER TABLE ONLY public.core_newsletter
    ADD CONSTRAINT core_newsletter_email_key UNIQUE (email);


--
-- Name: core_newsletter core_newsletter_pkey; Type: CONSTRAINT; Schema: public; Owner: bathudi_user
--

ALTER TABLE ONLY public.core_newsletter
    ADD CONSTRAINT core_newsletter_pkey PRIMARY KEY (id);


--
-- Name: core_newspost core_newspost_pkey; Type: CONSTRAINT; Schema: public; Owner: bathudi_user
--

ALTER TABLE ONLY public.core_newspost
    ADD CONSTRAINT core_newspost_pkey PRIMARY KEY (id);


--
-- Name: core_student core_student_application_id_key; Type: CONSTRAINT; Schema: public; Owner: bathudi_user
--

ALTER TABLE ONLY public.core_student
    ADD CONSTRAINT core_student_application_id_key UNIQUE (application_id);


--
-- Name: core_student core_student_pkey; Type: CONSTRAINT; Schema: public; Owner: bathudi_user
--

ALTER TABLE ONLY public.core_student
    ADD CONSTRAINT core_student_pkey PRIMARY KEY (id);


--
-- Name: core_student core_student_student_id_key; Type: CONSTRAINT; Schema: public; Owner: bathudi_user
--

ALTER TABLE ONLY public.core_student
    ADD CONSTRAINT core_student_student_id_key UNIQUE (student_id);


--
-- Name: core_student core_student_user_id_key; Type: CONSTRAINT; Schema: public; Owner: bathudi_user
--

ALTER TABLE ONLY public.core_student
    ADD CONSTRAINT core_student_user_id_key UNIQUE (user_id);


--
-- Name: core_teammember core_teammember_pkey; Type: CONSTRAINT; Schema: public; Owner: bathudi_user
--

ALTER TABLE ONLY public.core_teammember
    ADD CONSTRAINT core_teammember_pkey PRIMARY KEY (id);


--
-- Name: core_testimonial core_testimonial_pkey; Type: CONSTRAINT; Schema: public; Owner: bathudi_user
--

ALTER TABLE ONLY public.core_testimonial
    ADD CONSTRAINT core_testimonial_pkey PRIMARY KEY (id);


--
-- Name: core_video core_video_pkey; Type: CONSTRAINT; Schema: public; Owner: bathudi_user
--

ALTER TABLE ONLY public.core_video
    ADD CONSTRAINT core_video_pkey PRIMARY KEY (id);


--
-- Name: django_admin_log django_admin_log_pkey; Type: CONSTRAINT; Schema: public; Owner: bathudi_user
--

ALTER TABLE ONLY public.django_admin_log
    ADD CONSTRAINT django_admin_log_pkey PRIMARY KEY (id);


--
-- Name: django_content_type django_content_type_app_label_model_76bd3d3b_uniq; Type: CONSTRAINT; Schema: public; Owner: bathudi_user
--

ALTER TABLE ONLY public.django_content_type
    ADD CONSTRAINT django_content_type_app_label_model_76bd3d3b_uniq UNIQUE (app_label, model);


--
-- Name: django_content_type django_content_type_pkey; Type: CONSTRAINT; Schema: public; Owner: bathudi_user
--

ALTER TABLE ONLY public.django_content_type
    ADD CONSTRAINT django_content_type_pkey PRIMARY KEY (id);


--
-- Name: django_migrations django_migrations_pkey; Type: CONSTRAINT; Schema: public; Owner: bathudi_user
--

ALTER TABLE ONLY public.django_migrations
    ADD CONSTRAINT django_migrations_pkey PRIMARY KEY (id);


--
-- Name: django_session django_session_pkey; Type: CONSTRAINT; Schema: public; Owner: bathudi_user
--

ALTER TABLE ONLY public.django_session
    ADD CONSTRAINT django_session_pkey PRIMARY KEY (session_key);


--
-- Name: payfast_payfasttransaction payfast_payfasttransaction_payment_id_key; Type: CONSTRAINT; Schema: public; Owner: bathudi_user
--

ALTER TABLE ONLY public.payfast_payfasttransaction
    ADD CONSTRAINT payfast_payfasttransaction_payment_id_key UNIQUE (payment_id);


--
-- Name: payfast_payfasttransaction payfast_payfasttransaction_pkey; Type: CONSTRAINT; Schema: public; Owner: bathudi_user
--

ALTER TABLE ONLY public.payfast_payfasttransaction
    ADD CONSTRAINT payfast_payfasttransaction_pkey PRIMARY KEY (id);


--
-- Name: auth_group_name_a6ea08ec_like; Type: INDEX; Schema: public; Owner: bathudi_user
--

CREATE INDEX auth_group_name_a6ea08ec_like ON public.auth_group USING btree (name varchar_pattern_ops);


--
-- Name: auth_group_permissions_group_id_b120cbf9; Type: INDEX; Schema: public; Owner: bathudi_user
--

CREATE INDEX auth_group_permissions_group_id_b120cbf9 ON public.auth_group_permissions USING btree (group_id);


--
-- Name: auth_group_permissions_permission_id_84c5c92e; Type: INDEX; Schema: public; Owner: bathudi_user
--

CREATE INDEX auth_group_permissions_permission_id_84c5c92e ON public.auth_group_permissions USING btree (permission_id);


--
-- Name: auth_permission_content_type_id_2f476e4b; Type: INDEX; Schema: public; Owner: bathudi_user
--

CREATE INDEX auth_permission_content_type_id_2f476e4b ON public.auth_permission USING btree (content_type_id);


--
-- Name: auth_user_groups_group_id_97559544; Type: INDEX; Schema: public; Owner: bathudi_user
--

CREATE INDEX auth_user_groups_group_id_97559544 ON public.auth_user_groups USING btree (group_id);


--
-- Name: auth_user_groups_user_id_6a12ed8b; Type: INDEX; Schema: public; Owner: bathudi_user
--

CREATE INDEX auth_user_groups_user_id_6a12ed8b ON public.auth_user_groups USING btree (user_id);


--
-- Name: auth_user_user_permissions_permission_id_1fbb5f2c; Type: INDEX; Schema: public; Owner: bathudi_user
--

CREATE INDEX auth_user_user_permissions_permission_id_1fbb5f2c ON public.auth_user_user_permissions USING btree (permission_id);


--
-- Name: auth_user_user_permissions_user_id_a95ead1b; Type: INDEX; Schema: public; Owner: bathudi_user
--

CREATE INDEX auth_user_user_permissions_user_id_a95ead1b ON public.auth_user_user_permissions USING btree (user_id);


--
-- Name: auth_user_username_6821ab7c_like; Type: INDEX; Schema: public; Owner: bathudi_user
--

CREATE INDEX auth_user_username_6821ab7c_like ON public.auth_user USING btree (username varchar_pattern_ops);


--
-- Name: core_application_course_id_4dd7a704; Type: INDEX; Schema: public; Owner: bathudi_user
--

CREATE INDEX core_application_course_id_4dd7a704 ON public.core_application USING btree (course_id);


--
-- Name: core_application_payment_reference_b437c17a_like; Type: INDEX; Schema: public; Owner: bathudi_user
--

CREATE INDEX core_application_payment_reference_b437c17a_like ON public.core_application USING btree (payment_reference varchar_pattern_ops);


--
-- Name: core_courserequirement_course_id_598f48c3; Type: INDEX; Schema: public; Owner: bathudi_user
--

CREATE INDEX core_courserequirement_course_id_598f48c3 ON public.core_courserequirement USING btree (course_id);


--
-- Name: core_newsletter_email_78f32592_like; Type: INDEX; Schema: public; Owner: bathudi_user
--

CREATE INDEX core_newsletter_email_78f32592_like ON public.core_newsletter USING btree (email varchar_pattern_ops);


--
-- Name: core_student_course_id_43fa298f; Type: INDEX; Schema: public; Owner: bathudi_user
--

CREATE INDEX core_student_course_id_43fa298f ON public.core_student USING btree (course_id);


--
-- Name: core_student_student_id_4b8cfd3a_like; Type: INDEX; Schema: public; Owner: bathudi_user
--

CREATE INDEX core_student_student_id_4b8cfd3a_like ON public.core_student USING btree (student_id varchar_pattern_ops);


--
-- Name: core_testimonial_course_id_37725886; Type: INDEX; Schema: public; Owner: bathudi_user
--

CREATE INDEX core_testimonial_course_id_37725886 ON public.core_testimonial USING btree (course_id);


--
-- Name: django_admin_log_content_type_id_c4bce8eb; Type: INDEX; Schema: public; Owner: bathudi_user
--

CREATE INDEX django_admin_log_content_type_id_c4bce8eb ON public.django_admin_log USING btree (content_type_id);


--
-- Name: django_admin_log_user_id_c564eba6; Type: INDEX; Schema: public; Owner: bathudi_user
--

CREATE INDEX django_admin_log_user_id_c564eba6 ON public.django_admin_log USING btree (user_id);


--
-- Name: django_session_expire_date_a5c62663; Type: INDEX; Schema: public; Owner: bathudi_user
--

CREATE INDEX django_session_expire_date_a5c62663 ON public.django_session USING btree (expire_date);


--
-- Name: django_session_session_key_c0390e0f_like; Type: INDEX; Schema: public; Owner: bathudi_user
--

CREATE INDEX django_session_session_key_c0390e0f_like ON public.django_session USING btree (session_key varchar_pattern_ops);


--
-- Name: payfast_payfasttransaction_payment_id_31e73a67_like; Type: INDEX; Schema: public; Owner: bathudi_user
--

CREATE INDEX payfast_payfasttransaction_payment_id_31e73a67_like ON public.payfast_payfasttransaction USING btree (payment_id varchar_pattern_ops);


--
-- Name: auth_group_permissions auth_group_permissio_permission_id_84c5c92e_fk_auth_perm; Type: FK CONSTRAINT; Schema: public; Owner: bathudi_user
--

ALTER TABLE ONLY public.auth_group_permissions
    ADD CONSTRAINT auth_group_permissio_permission_id_84c5c92e_fk_auth_perm FOREIGN KEY (permission_id) REFERENCES public.auth_permission(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: auth_group_permissions auth_group_permissions_group_id_b120cbf9_fk_auth_group_id; Type: FK CONSTRAINT; Schema: public; Owner: bathudi_user
--

ALTER TABLE ONLY public.auth_group_permissions
    ADD CONSTRAINT auth_group_permissions_group_id_b120cbf9_fk_auth_group_id FOREIGN KEY (group_id) REFERENCES public.auth_group(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: auth_permission auth_permission_content_type_id_2f476e4b_fk_django_co; Type: FK CONSTRAINT; Schema: public; Owner: bathudi_user
--

ALTER TABLE ONLY public.auth_permission
    ADD CONSTRAINT auth_permission_content_type_id_2f476e4b_fk_django_co FOREIGN KEY (content_type_id) REFERENCES public.django_content_type(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: auth_user_groups auth_user_groups_group_id_97559544_fk_auth_group_id; Type: FK CONSTRAINT; Schema: public; Owner: bathudi_user
--

ALTER TABLE ONLY public.auth_user_groups
    ADD CONSTRAINT auth_user_groups_group_id_97559544_fk_auth_group_id FOREIGN KEY (group_id) REFERENCES public.auth_group(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: auth_user_groups auth_user_groups_user_id_6a12ed8b_fk_auth_user_id; Type: FK CONSTRAINT; Schema: public; Owner: bathudi_user
--

ALTER TABLE ONLY public.auth_user_groups
    ADD CONSTRAINT auth_user_groups_user_id_6a12ed8b_fk_auth_user_id FOREIGN KEY (user_id) REFERENCES public.auth_user(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: auth_user_user_permissions auth_user_user_permi_permission_id_1fbb5f2c_fk_auth_perm; Type: FK CONSTRAINT; Schema: public; Owner: bathudi_user
--

ALTER TABLE ONLY public.auth_user_user_permissions
    ADD CONSTRAINT auth_user_user_permi_permission_id_1fbb5f2c_fk_auth_perm FOREIGN KEY (permission_id) REFERENCES public.auth_permission(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: auth_user_user_permissions auth_user_user_permissions_user_id_a95ead1b_fk_auth_user_id; Type: FK CONSTRAINT; Schema: public; Owner: bathudi_user
--

ALTER TABLE ONLY public.auth_user_user_permissions
    ADD CONSTRAINT auth_user_user_permissions_user_id_a95ead1b_fk_auth_user_id FOREIGN KEY (user_id) REFERENCES public.auth_user(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: core_application core_application_course_id_4dd7a704_fk_core_course_id; Type: FK CONSTRAINT; Schema: public; Owner: bathudi_user
--

ALTER TABLE ONLY public.core_application
    ADD CONSTRAINT core_application_course_id_4dd7a704_fk_core_course_id FOREIGN KEY (course_id) REFERENCES public.core_course(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: core_courserequirement core_courserequirement_course_id_598f48c3_fk_core_course_id; Type: FK CONSTRAINT; Schema: public; Owner: bathudi_user
--

ALTER TABLE ONLY public.core_courserequirement
    ADD CONSTRAINT core_courserequirement_course_id_598f48c3_fk_core_course_id FOREIGN KEY (course_id) REFERENCES public.core_course(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: core_student core_student_application_id_5327b928_fk_core_application_id; Type: FK CONSTRAINT; Schema: public; Owner: bathudi_user
--

ALTER TABLE ONLY public.core_student
    ADD CONSTRAINT core_student_application_id_5327b928_fk_core_application_id FOREIGN KEY (application_id) REFERENCES public.core_application(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: core_student core_student_course_id_43fa298f_fk_core_course_id; Type: FK CONSTRAINT; Schema: public; Owner: bathudi_user
--

ALTER TABLE ONLY public.core_student
    ADD CONSTRAINT core_student_course_id_43fa298f_fk_core_course_id FOREIGN KEY (course_id) REFERENCES public.core_course(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: core_student core_student_user_id_666ccffd_fk_auth_user_id; Type: FK CONSTRAINT; Schema: public; Owner: bathudi_user
--

ALTER TABLE ONLY public.core_student
    ADD CONSTRAINT core_student_user_id_666ccffd_fk_auth_user_id FOREIGN KEY (user_id) REFERENCES public.auth_user(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: core_testimonial core_testimonial_course_id_37725886_fk_core_course_id; Type: FK CONSTRAINT; Schema: public; Owner: bathudi_user
--

ALTER TABLE ONLY public.core_testimonial
    ADD CONSTRAINT core_testimonial_course_id_37725886_fk_core_course_id FOREIGN KEY (course_id) REFERENCES public.core_course(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: django_admin_log django_admin_log_content_type_id_c4bce8eb_fk_django_co; Type: FK CONSTRAINT; Schema: public; Owner: bathudi_user
--

ALTER TABLE ONLY public.django_admin_log
    ADD CONSTRAINT django_admin_log_content_type_id_c4bce8eb_fk_django_co FOREIGN KEY (content_type_id) REFERENCES public.django_content_type(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: django_admin_log django_admin_log_user_id_c564eba6_fk_auth_user_id; Type: FK CONSTRAINT; Schema: public; Owner: bathudi_user
--

ALTER TABLE ONLY public.django_admin_log
    ADD CONSTRAINT django_admin_log_user_id_c564eba6_fk_auth_user_id FOREIGN KEY (user_id) REFERENCES public.auth_user(id) DEFERRABLE INITIALLY DEFERRED;


--
-- PostgreSQL database dump complete
--

\unrestrict Yy0ilq75Xfg2VTHKkBvkrNpckdbmUmtRKqjZupP7iD9mBzK9u7tjfB34MOmmmYO

