# Generated by Django 6.0.1 on 2026-01-22 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='assessment_fee',
            field=models.DecimalField(decimal_places=2, default=661.25, help_text='Assessment fee', max_digits=10),
        ),
        migrations.AddField(
            model_name='course',
            name='course_pdf',
            field=models.FileField(blank=True, help_text='PDF file with full course details', null=True, upload_to='course_pdfs/'),
        ),
        migrations.AddField(
            model_name='course',
            name='credits',
            field=models.IntegerField(default=0, help_text='Number of credits for the course'),
        ),
        migrations.AddField(
            model_name='course',
            name='deposit_amount',
            field=models.DecimalField(decimal_places=2, default=6612.5, help_text='Deposit amount', max_digits=10),
        ),
        migrations.AddField(
            model_name='course',
            name='monthly_payment',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Monthly payment amount', max_digits=10),
        ),
        migrations.AddField(
            model_name='course',
            name='total_payment',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Total payment for the course', max_digits=10),
        ),
    ]
