# Generated by Django 6.0.1 on 2026-01-22 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_course_assessment_fee_course_course_pdf_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='course_pdf_url',
            field=models.CharField(blank=True, help_text='External PDF URL or static file path', max_length=500),
        ),
    ]
