# Generated by Django 6.0.1 on 2026-02-01 14:04

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_course_course_pdf_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='additional_doc_1',
            field=models.FileField(blank=True, null=True, upload_to='applications/additional_docs/', validators=[django.core.validators.FileExtensionValidator(['pdf', 'jpg', 'jpeg', 'png', 'doc', 'docx'])]),
        ),
        migrations.AddField(
            model_name='application',
            name='additional_doc_2',
            field=models.FileField(blank=True, null=True, upload_to='applications/additional_docs/', validators=[django.core.validators.FileExtensionValidator(['pdf', 'jpg', 'jpeg', 'png', 'doc', 'docx'])]),
        ),
        migrations.AddField(
            model_name='application',
            name='address',
            field=models.TextField(blank=True, help_text='Physical address'),
        ),
        migrations.AddField(
            model_name='application',
            name='course_title',
            field=models.CharField(blank=True, help_text='Full course title', max_length=200),
        ),
        migrations.AddField(
            model_name='application',
            name='id_number',
            field=models.CharField(blank=True, help_text='ID or Passport number', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='application',
            name='id_document',
            field=models.FileField(blank=True, null=True, upload_to='applications/id_documents/', validators=[django.core.validators.FileExtensionValidator(['pdf', 'jpg', 'jpeg', 'png'])]),
        ),
        migrations.AlterField(
            model_name='application',
            name='matric_certificate',
            field=models.FileField(blank=True, null=True, upload_to='applications/matric_certificates/', validators=[django.core.validators.FileExtensionValidator(['pdf', 'jpg', 'jpeg', 'png'])]),
        ),
        migrations.AlterField(
            model_name='application',
            name='proof_of_payment',
            field=models.FileField(blank=True, null=True, upload_to='applications/proof_of_payments/', validators=[django.core.validators.FileExtensionValidator(['pdf', 'jpg', 'jpeg', 'png'])]),
        ),
    ]
