# Generated by Django 6.0.1 on 2026-02-11 08:02

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_application_additional_doc_1_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='form_course_id',
            field=models.CharField(blank=True, help_text='Course ID from the form', max_length=100),
        ),
        migrations.AlterField(
            model_name='application',
            name='additional_doc_1',
            field=models.FileField(blank=True, null=True, upload_to='applications/additional_docs/%Y/%m/%d/', validators=[django.core.validators.FileExtensionValidator(['pdf', 'jpg', 'jpeg', 'png', 'doc', 'docx'])]),
        ),
        migrations.AlterField(
            model_name='application',
            name='additional_doc_2',
            field=models.FileField(blank=True, null=True, upload_to='applications/additional_docs/%Y/%m/%d/', validators=[django.core.validators.FileExtensionValidator(['pdf', 'jpg', 'jpeg', 'png', 'doc', 'docx'])]),
        ),
        migrations.AlterField(
            model_name='application',
            name='country',
            field=models.CharField(default='South Africa', max_length=100),
        ),
        migrations.AlterField(
            model_name='application',
            name='course',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='applications', to='core.course'),
        ),
        migrations.AlterField(
            model_name='application',
            name='id_document',
            field=models.FileField(blank=True, null=True, upload_to='applications/id_documents/%Y/%m/%d/', validators=[django.core.validators.FileExtensionValidator(['pdf', 'jpg', 'jpeg', 'png'])]),
        ),
        migrations.AlterField(
            model_name='application',
            name='matric_certificate',
            field=models.FileField(blank=True, null=True, upload_to='applications/matric_certificates/%Y/%m/%d/', validators=[django.core.validators.FileExtensionValidator(['pdf', 'jpg', 'jpeg', 'png'])]),
        ),
        migrations.AlterField(
            model_name='application',
            name='proof_of_payment',
            field=models.FileField(blank=True, null=True, upload_to='applications/proof_of_payments/%Y/%m/%d/', validators=[django.core.validators.FileExtensionValidator(['pdf', 'jpg', 'jpeg', 'png'])]),
        ),
    ]
