# Generated by Django 6.0.1 on 2026-02-11 11:19

import core.models
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_application_form_course_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='country',
            field=models.CharField(choices=[('South Africa', 'South Africa'), ('Lesotho', 'Lesotho'), ('Botswana', 'Botswana'), ('Eswatini', 'Eswatini'), ('Namibia', 'Namibia'), ('Zimbabwe', 'Zimbabwe'), ('Mozambique', 'Mozambique'), ('Zambia', 'Zambia'), ('Other African Country', 'Other African Country'), ('International', 'International')], default='South Africa', max_length=100),
        ),
        migrations.AlterField(
            model_name='application',
            name='id_document',
            field=models.FileField(blank=True, null=True, upload_to=core.models.id_document_upload_path, validators=[django.core.validators.FileExtensionValidator(['pdf', 'jpg', 'jpeg', 'png'])]),
        ),
        migrations.AlterField(
            model_name='application',
            name='matric_certificate',
            field=models.FileField(blank=True, null=True, upload_to=core.models.matric_certificate_upload_path, validators=[django.core.validators.FileExtensionValidator(['pdf', 'jpg', 'jpeg', 'png'])]),
        ),
        migrations.AlterField(
            model_name='application',
            name='proof_of_payment',
            field=models.FileField(blank=True, null=True, upload_to=core.models.proof_of_payment_upload_path, validators=[django.core.validators.FileExtensionValidator(['pdf', 'jpg', 'jpeg', 'png'])]),
        ),
    ]
