# Generated by Django 6.0.1 on 2026-03-19 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_application_rejection_reason'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='payment_reference',
            field=models.CharField(blank=True, help_text='PayFast m_payment_id', max_length=100, null=True, unique=True),
        ),
    ]
