# Generated by Django 4.2 on 2026-04-07 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_alter_student_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='registration_fee',
            field=models.DecimalField(decimal_places=2, default=661.25, help_text='Non-refundable registration fee', max_digits=10),
        ),
    ]
